float i = 0;
PImage[] imagenes;
int piedrasVelocidad = 4;
int rocaVelocidad = 1;
int coralVelocidad = 7;
float coralSize = 1;
float rocaSize = 1;
float piedraSize = 1;
float posxp = -140;
float posxc = 200;
float posxr = 500;
PImage piedra;
PImage roca;
PImage corales;
PImage[] medusas;
float velocidad = 0.07;
float movimiento = 100;
PImage fondo;
float x = 0;
int marVelocidad = 2;
float posy = 200;
float posx = 100;
boolean yendo = true;
PImage[] sonar;
boolean sonarActivo = false;
float s = 0;
float posxm = 700;
float posym = 100;
float m = 0;
float amplitud = 4;
float frecuencia = 0.05;
boolean muerto = false;
int fondoAncho = 690;
float marx1 = 0;
float marx2 = 690;//fondoAncho
boolean mostrarBoundingBox=false;
SoundFile sonido;
